#!/usr/bin/env bash
# build.sh — Assembles src/* into a single bin/termifun executable
# Usage: ./build.sh

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
SRC_DIR="$SCRIPT_DIR/src"
OUT_FILE="$SCRIPT_DIR/bin/termifun"

# Ordered list of source modules
MODULES=(
  "$SRC_DIR/data.sh"
  "$SRC_DIR/core.sh"
  "$SRC_DIR/ui.sh"
  "$SRC_DIR/main.sh"
)

# Verify all modules exist before writing anything
for f in "${MODULES[@]}"; do
  if [ ! -f "$f" ]; then
    printf 'ERROR: Missing module: %s\n' "$f" >&2
    exit 1
  fi
done

{
  # ── Shebang and header ───────────────────────────
  printf '#!/usr/bin/env bash\n'
  printf '# termifun - CLI Fun Tools Launcher\n'
  printf '# https://github.com/P1ngu-Dev/termifun\n'
  printf '# License: MIT\n'
  printf '#\n'
  printf '# !! AUTO-GENERATED by build.sh — do not edit directly !!\n'
  printf '# Edit the source files in src/ and run ./build.sh to regenerate.\n'
  printf '#\n'
  printf '# Source layout:\n'
  printf '#   src/data.sh  — VERSION + FUN_TOOLS definitions\n'
  printf '#   src/core.sh  — Colors, pkg manager, tool scanning\n'
  printf '#   src/ui.sh    — Interactive menus and display\n'
  printf '#   src/main.sh  — UI loop and argument parsing\n'
  printf '\n'

  # ── Inline each module (skip shebangs/blank leading lines) ──
  for module in "${MODULES[@]}"; do
    name="$(basename "$module")"
    printf '# ════════════════════════════════════════════════════════\n'
    printf '# MODULE: %s\n' "$name"
    printf '# ════════════════════════════════════════════════════════\n'
    # Skip any #!/... shebang lines that might be at top of modules
    grep -v '^#!' "$module"
    printf '\n'
  done
} > "$OUT_FILE"

chmod +x "$OUT_FILE"

# Validate the generated script
if bash -n "$OUT_FILE"; then
  printf '✔ Build successful → %s\n' "$OUT_FILE"
else
  printf '✘ Build produced an invalid script. Check src/ for errors.\n' >&2
  exit 1
fi
